# frozen_string_literal: true

ruby '2.5.1'
source 'https://rubygems.org'

gem 'redis-namespace'
gem 'sidekiq-scheduler'
gem 'twitter'

group :development, :test do
  gem 'byebug'
  gem 'rspec'
  gem 'vcr'
  gem 'webmock'
end
